# Generated by Django 3.2.7 on 2021-10-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_articlestatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
