# Generated by Django 3.2.7 on 2021-10-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_articlestatistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
