# Generated by Django 3.2.7 on 2021-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_articlestatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
