# Generated by Django 3.2.7 on 2021-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20211005_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Просмотры'),
        ),
    ]
