# Generated by Django 3.2.8 on 2021-10-09 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0014_alter_movie_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.BooleanField(default=False)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
