# Generated by Django 3.2.8 on 2021-10-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_studentapplying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplying',
            name='applied',
            field=models.IntegerField(default=0),
        ),
    ]
