# Generated by Django 3.2.8 on 2021-10-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_studentapplying_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.IntegerField(default=0)),
                ('movieName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentApplying',
        ),
    ]
