# Generated by Django 3.2.8 on 2021-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_updateviews_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateviews',
            name='applied',
            field=models.IntegerField(default=0),
        ),
    ]
