# Generated by Django 3.2.8 on 2022-01-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveSmallIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
    ]
