# Generated by Django 3.2.8 on 2022-01-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveBigIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveBigIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в США'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveBigIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Сборы в мире'),
        ),
    ]
