# Generated by Django 3.2.8 on 2022-01-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_alter_movie_fees_in_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Дата выхода')),
            ],
        ),
    ]
