# Generated by Django 3.2.8 on 2022-01-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
